;
; UTF-8(with BOM)
;
[ExtractBootWIM]
0 = /sources/boot.wim
1 = /x64/sources/boot.wim
2 = /x86/sources/boot.wim

[ExtractFileFromBootWIM]
bios_0 = /windows/boot/DVD/PCAT/etfsboot.com, %CURRENTDIR%\work\tmp
uefi_0 = /windows/boot/DVD/EFI/en-US/efisys.bin, %CURRENTDIR%\work\tmp

[ExtractFileFromBootWIM_BIOS]
0 = /windows/boot/PCAT/bootmgr, %CURRENTDIR%\work\media
1 = /windows/boot/DVD/PCAT/etfsboot.com, %CURRENTDIR%\work\media\boot
2 = /windows/boot/DVD/PCAT/en-US/*, %CURRENTDIR%\work\media\boot
3 = /windows/boot/DVD/PCAT/*, %CURRENTDIR%\work\media\boot
4 = /windows/boot/DVD/PCAT/*, %CURRENTDIR%\work\media\EFI\Microsoft\boot
5 = /windows/boot/Fonts/*, %CURRENTDIR%\work\media\EFI\Microsoft\boot\Fonts
6 = /windows/boot/Fonts/*, %CURRENTDIR%\work\media\boot\Fonts
7 = /windows/boot/Resources/*, %CURRENTDIR%\work\media\EFI\Microsoft\boot\Resources
registry_0 = /windows/system32/config/software, %CURRENTDIR%\work\tmp

[ExtractFileFromBootWIM_UEFI]
0 = /windows/boot/EFI/bootmgr.efi, %CURRENTDIR%\work\media
1 = /windows/boot/DVD/EFI/en-US/efisys.bin, %CURRENTDIR%\work\media\boot
;rename_1 = /windows/boot/DVD/EFI/en-US/efisys_noprompt.bin, %CURRENTDIR%\work\media\boot\efisys.bin
2 = /windows/boot/DVD/EFI/*, %CURRENTDIR%\work\media\boot
3 = /windows/boot/DVD/EFI/*, %CURRENTDIR%\work\media\EFI\Microsoft\boot
4 = /windows/boot/Fonts/*, %CURRENTDIR%\work\media\EFI\Microsoft\boot\Fonts
5 = /windows/boot/Fonts/*, %CURRENTDIR%\work\media\boot\Fonts
6 = /windows/boot/Resources/*, %CURRENTDIR%\work\media\EFI\Microsoft\boot\Resources
rename_0 = /windows/boot/EFI/bootmgfw.efi, %CURRENTDIR%\work\media\EFI\boot\bootx64.efi
registry_0 = /windows/system32/config/software, %CURRENTDIR%\work\tmp

[ExtractFolderFromISO]
;sample = /boot, %CURRENTDIR%\work\media

[ExtractFileFromISO]
;sample = /bootmgr, %CURRENTDIR%\work\media\bootmgr

[CopyFile]
;sample = %CURRENTDIR%\test.txt, %CURRENTDIR%\work\media\test.txt

[Delete]
0 = /setup.exe
1 = /Windows/System32/winpeshl.ini

[Add_x64]
0 = %CURRENTDIR%\work\tmp\winpeshl.ini, /Windows/System32/winpeshl.ini
App0 = %CURRENTDIR%\UBR64.exe, /Program Files/UBR/UBR64.exe
App1 = %CURRENTDIR%\lang, /Program Files/UBR/lang
App2 = %CURRENTDIR%\UBR32.exe, /Program Files (x86)/UBR/UBR32.exe
App3 = %CURRENTDIR%\lang, /Program Files (x86)/UBR/lang

[Add_x86]
0 = %CURRENTDIR%\work\tmp\winpeshl.ini, /Windows/System32/winpeshl.ini
App0 = %CURRENTDIR%\UBR32.exe, /Program Files/UBR/UBR32.exe
App1 = %CURRENTDIR%\lang, /Program Files/UBR/lang

[winpeshl.ini_x64]
key = <<<ENDTAG
[LaunchApp]
AppPath = %SYSTEMDRIVE%\Program Files\UBR\UBR64.exe

ENDTAG

[winpeshl.ini_x86]
key = <<<ENDTAG
[LaunchApp]
AppPath = %SYSTEMDRIVE%\Program Files\UBR\UBR32.exe

ENDTAG
